baseURL = "https://ic0nml.github.io"
languageCode = "en-us"
title = "ICON.ML Blog"
theme = "hugo-theme-cleanwhite-rsy"

paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/main_go_wideandtall_darklayer.jpeg"
  title = "ML Notes and Codes"
  slogan = "WTM"
  SEOTitle = "PLTW Blog"
  keyword = "ML, AI, DL"
 
  # Sidebar settings
  #sidebar_about_description = "Me"
  #sidebar_avatar = "images/MeAtJackson.jpeg"
  #about_me = true

  #featured_tags = true 
  #featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  #rss            = true
  #email          = "rich.youngkin@gmail.com"
  #linkedin       = "https://www.linkedin.com/in/richard-youngkin-0749763"
  #github         = "https://github.com/youngkin"
  #medium         = "https://medium.com/@RichYoungkin"
  #stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  #reddit         = "https://www.reddit.com/user/elevation5280"